// <define:__ROUTES__>
var define_ROUTES_default = {
  version: 1,
  description: "Generated by @sveltejs/adapter-cloudflare",
  include: [
    "/*"
  ],
  exclude: [
    "/_app/*",
    "/favicon.png",
    "/robots.txt",
    "/",
    "/about"
  ]
};

// ../../node_modules/.pnpm/wrangler@3.90.0_@cloudflare+workers-types@4.20241112.0/node_modules/wrangler/templates/pages-dev-pipeline.ts
import worker from "/Users/benmackie/dev/repl/repl-cfrpc-a/packages/webapp/.wrangler/tmp/pages-d0qgfW/bundledWorker-0.9366450401221305.mjs";
import { isRoutingRuleMatch } from "/Users/benmackie/dev/repl/repl-cfrpc-a/node_modules/.pnpm/wrangler@3.90.0_@cloudflare+workers-types@4.20241112.0/node_modules/wrangler/templates/pages-dev-util.ts";
export * from "/Users/benmackie/dev/repl/repl-cfrpc-a/packages/webapp/.wrangler/tmp/pages-d0qgfW/bundledWorker-0.9366450401221305.mjs";
var routes = define_ROUTES_default;
var pages_dev_pipeline_default = {
  fetch(request, env, context) {
    const { pathname } = new URL(request.url);
    for (const exclude of routes.exclude) {
      if (isRoutingRuleMatch(pathname, exclude)) {
        return env.ASSETS.fetch(request);
      }
    }
    for (const include of routes.include) {
      if (isRoutingRuleMatch(pathname, include)) {
        if (worker.fetch === void 0) {
          throw new TypeError("Entry point missing `fetch` handler");
        }
        return worker.fetch(request, env, context);
      }
    }
    return env.ASSETS.fetch(request);
  }
};
export {
  pages_dev_pipeline_default as default
};
//# sourceMappingURL=m0y02h1qbw.js.map
