// Generated by Wrangler by running `wrangler types`

type NotifyService = {
	notify(msg: string): Promise<void>;
};

export type CloudflareWorkerEntrypoint<T> = {
	[Rpc.__WORKER_ENTRYPOINT_BRAND]: never; // To satisfy the Cloudflare type system.
} & T;

type NotifyWorker = Service<CloudflareWorkerEntrypoint<NotifyService>>;

// eslint-disable-next-line @typescript-eslint/no-empty-interface,@typescript-eslint/no-empty-object-type
interface Env {
    NOTIFY_WORKER: NotifyWorker;
}
